services:
  redis:
    image: redis:7-alpine
    container_name: mailbridge-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  mailbridge:
    build: .
    container_name: mailbridge
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=2525
      - INSTANCE_EMAILS=info@example.com,contact@website.com
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config:/config
    ports:
      - "2525:2525"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

volumes:
  redis_data:
