global:
    smtp:
        host: smtp.mail.me.com  # iCloud SMTP server
        port: 587
        user: ${ICLOUD_EMAIL}
        password: ${ICLOUD_PASSWORD}
        disable_tls: false

forms:
    example-contact:
        key: example-contact-key
        allowed_domains:
            - example.com
            - www.example.com
            - site.example.com
        to_email:
            - info@example.com
        from_name: Example Team

    example2-contact:
        key: example2-contact-key
        allowed_domains:
            - website.com
            - www.website.com
            - site.website.com
        to_email:
            - contact@website.com
        from_name: First Last 
